version: '3'

services:
database:
    build:
      #image: mdillon/postgis:latest
      context: ./docker-postgres-wale
      dockerfile: Dockerfile
      #image: mdillon/postgis:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
      - WALE_FILE_PREFIX=file://var/lib/postgresql/backup/
      - EDITOR=/usr/bin/vi
        #'file://localhost/backups/pg'
    ports:
        - 5432:5432
    volumes:
      - postgis_data_volume:/var/lib/postgresql/data
      - postgis_backup_volume:/lib/postgresql/backup
      - postgis_env_volume:/etc/wal-e.d/env
volumes:
    postgis_data_volume:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/root/smartaqnet-dev/volumes/frost/postgis_data_volume'
    postgis_backup_volume:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/root/smartaqnet-dev/volumes/frost/postgis_backup_volume'
    postgis_env_volume:
